# Generated by Django 4.2.5 on 2023-10-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="sha256",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
