# Generated by Django 4.2.4 on 2023-09-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="original_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
