# Generated by Django 4.2.4 on 2023-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("SYS", "System Message"),
                    ("USER", "User Message"),
                    ("CONTEXT", "Vector DB Context"),
                    ("LLM", "LLM Response"),
                ],
                max_length=10,
            ),
        ),
    ]
