# Generated by Django 4.2.4 on 2023-09-10 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["updated_at"]},
        ),
    ]
