# Generated by Django 4.2.5 on 2023-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_documentfile_original_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="file",
            field=models.FileField(upload_to="user_files/"),
        ),
    ]
